project:
  type: website
  output-dir: docs
  
website:
  title: "UNH R Users Group Websire"
  favicon: 
  navbar:
    background: "#43CD80" 
    foreground: "#000000"
    search: false
    left:
      - text: Home
        href: index.qmd
      - text: Schedule & Materials
        href: schedule.qmd
      - text: Instructors
        href: instructors.qmd
    tools:
      - icon: github
        href:  https://github.com/QuantMarineEcoLab/r_by_the_sea
  page-footer: 
    left: "Made by EMW & ERW (2024) & Forked by FGF (2024)" 
    right: "Powered by Quarto"
        
format:
  html:
    theme: lumen
    css: custom.css
    anchor-sections: false

execute:
  freeze: auto
