project:
  type: website
  output-dir: docs
  
website:
  title: "UNH R Users Group Website"
  navbar:
    background: "#43CD80" 
    foreground: "#000000"
    search: false
    left:
      - text: Home
        href: index.qmd
      - text: Schedule & Materials
        href: schedule.qmd
      - text: Instructors
        href: instructors.qmd
    tools:
      - icon: github
        href:  https://github.com/UNH-R-Users-Group/website
  page-footer: 
    right: "Powered by Quarto"
        
format:
  html:
    theme: lumen
    css: custom.css
    anchor-sections: false

execute:
  freeze: auto
