---
title: "Intro to Quarto"
format: html
editor: visual
execute: 
  echo: false
warning: false
editor_options: 
  chunk_output_type: console
bibliography: references.bib
csl: apa-annotated-bibliography.csl
---

# 

## Data

For this analysis we'll use the penguins dataset from the [palmerpenguins](https://allisonhorst.github.io/palmerpenguins/) package @gorman2014.

```{r}
library(tidyverse)
library(ggthemes)
library(palmerpenguins)
library(gt)
```

```{r}
data(penguins)
glimpse(penguins)
```

# 

## Species

Below is a bar plot of species of penguins.

```{r}
#| label: fig-bill-dims-species
#| fig-width: 5
#| fig-asp: 0.618
#| fig-cap: |
#|  A scatterplot of penguins' bill depth and length, colored by species of penguis. 


ggplot(
  penguins, 
  mapping = aes(
    x = bill_length_mm, y = bill_depth_mm, 
    color = species, shape = species
  )
)+
  geom_point()+
  theme_minimal() +
  scale_color_colorblind()+
  labs(x = "Bill Length (mm)", y = "Bill Depth (mm)")


```

# 

## Penguins

This table shows the first 10 penguins from the dataset.

```{r}
#| label: tbl-penguins-top10
#| tbl-cap: First 10 Penguins


penguins %>% 
  slice_head(n = 10) %>% 
  select(species, island, bill_length_mm, bill_depth_mm) %>% 
  gt()

```
